import { BlogPost } from "./types";

// This would typically come from a backend or CMS
// We're using localStorage for this demo
export const getBlogPosts = (): BlogPost[] => {
  const posts = localStorage.getItem("blog_posts");
  return posts ? JSON.parse(posts) : defaultPosts;
};

export const getBlogPostBySlug = (slug: string): BlogPost | undefined => {
  const posts = getBlogPosts();
  return posts.find((post) => post.slug === slug);
};

export const saveBlogPost = (post: BlogPost): void => {
  const posts = getBlogPosts();
  const existingPostIndex = posts.findIndex((p) => p.id === post.id);

  if (existingPostIndex >= 0) {
    // Update existing post
    posts[existingPostIndex] = post;
  } else {
    // Add new post
    posts.push(post);
  }

  localStorage.setItem("blog_posts", JSON.stringify(posts));
};

export const deleteBlogPost = (id: string): void => {
  const posts = getBlogPosts();
  const filteredPosts = posts.filter((post) => post.id !== id);
  localStorage.setItem("blog_posts", JSON.stringify(filteredPosts));
};

// Helper function to generate a slug from a title
export const slugify = (title: string): string => {
  return title
    .toLowerCase()
    .replace(/[^\w ]+/g, "")
    .replace(/ +/g, "-");
};

// Default posts that will be shown when no posts are created yet
const defaultPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Beauty of Chaos in Hardware Systems",
    slug: "beauty-of-chaos-hardware-systems",
    excerpt:
      "Exploring how chaotic systems can be harnessed for creating true randomness in computing applications.",
    content: `
# The Beauty of Chaos in Hardware Systems

Chaos theory tells us that certain systems, despite being deterministic, exhibit behavior that is practically unpredictable due to their extreme sensitivity to initial conditions. This phenomenon, sometimes called the "butterfly effect," has profound implications for computing.

## Why Randomness Matters

True randomness is surprisingly difficult to achieve in computing systems. Most "random" numbers generated by computers are actually pseudo-random—they follow deterministic algorithms that only appear random to an observer.

This becomes problematic in applications like:
- Cryptography
- Simulation
- Gaming
- Scientific modeling

## Harnessing Chaos for True Randomness

My journey into hardware-based random number generation began with a double pendulum. This simple mechanical system exhibits chaotic behavior that can be captured through computer vision techniques.

The setup involves:

1. A physical double pendulum
2. A camera tracking the motion
3. Computer vision software to extract position data
4. Algorithms to convert this physical entropy into random numbers

The beauty of this approach is that it taps into true physical randomness from the quantum and thermal fluctuations that affect the pendulum's motion.

## Results and Applications

Initial tests showed that the system passed standard randomness tests like NIST's Statistical Test Suite and Diehard. The numbers generated were indistinguishable from true random sequences.

This opens up possibilities for:
- Enhanced cryptographic applications
- More realistic simulations
- Fairer digital games of chance
- Novel approaches to AI training

## Looking Forward

The intersection of physical chaos and computing remains a fertile ground for innovation. I'm currently exploring ways to miniaturize this system and make hardware-based randomness more accessible.

Remember, in a world of deterministic algorithms, a touch of chaos might be exactly what we need.
    `,
    date: "2023-12-15",
    coverImage:
      "https://images.unsplash.com/photo-1597733336794-12d05021d510?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    tags: ["hardware", "randomness", "chaos-theory", "tech"],
  },
  {
    id: "2",
    title: "Quiet Mind, Loud World",
    slug: "quiet-mind-loud-world",
    excerpt:
      "A poem about finding stillness amidst the constant noise of modern existence.",
    content: `
# Quiet Mind, Loud World

In corners of silence I seek refuge,  
From the cacophony of pings and buzzes,  
The endless scroll of faces and places,  
That I should know, should go, should be.

The world crescendos in alarming time,  
While I conduct a symphony of breath,  
In, out, the only rhythm that matters  
When anxiety's orchestra swells too loud.

They say the universe is expanding,  
My universe contracts to this moment,  
This space between thoughts where I am free,  
From expectations, even my own.

A quiet mind in a loud world is rebellion,  
A radical act of being, not doing,  
Of listening for the spaces between noise,  
Where truth has always patiently waited.

Tomorrow I'll rejoin the world's chorus,  
But stronger for this moment of silence,  
Carrying peace like a secret power,  
That flickers even in the brightest rooms.
    `,
    date: "2024-01-23",
    tags: ["poetry", "mental-health", "mindfulness"],
  },
  {
    id: "3",
    title: "Reimagining Education Through Technology",
    slug: "reimagining-education-technology",
    excerpt:
      "Thoughts on how we can transform educational systems using AI and personalized learning approaches.",
    content: `
# Reimagining Education Through Technology

## The Current State

Our educational system remains largely unchanged from its industrial-era origins. Students still:
- Learn at the same pace
- Study the same subjects
- Take standardized tests
- Follow rigid curricula

This one-size-fits-all approach made sense for producing factory workers. It makes little sense for developing the creative, adaptable minds needed for the 21st century.

## The Technology Opportunity

We now have technologies that could fundamentally transform how we learn:

### AI-Driven Personalization

Imagine a learning system that adapts to each student's:
- Learning pace
- Preferred learning style (visual, auditory, kinesthetic)
- Areas of strength and weakness
- Interests and curiosities

AI tutoring systems can now provide targeted feedback and adjust difficulty in real-time, ensuring students are always in their "zone of proximal development" - challenged but not overwhelmed.

### Virtual and Augmented Reality

Why read about ancient Rome when you could walk through it? VR and AR can transform abstract concepts into tangible experiences:
- Explore cellular structures from the inside
- Conduct dangerous chemistry experiments safely
- Visit historical sites and events
- Visualize mathematical concepts in 3D space

### Collaborative Platforms

Technology can connect learners across vast distances:
- International project collaboration
- Peer teaching and learning
- Access to diverse perspectives
- Mentorship from experts globally

## My Vision

Through my work in education technology, I envision a system where:

1. **Learning is personalized** - Every student has a unique learning path
2. **Learning is experiential** - Students learn by doing, not just listening
3. **Learning is unbounded** - Not limited by classroom walls or national borders
4. **Learning is lifelong** - Education doesn't end with formal schooling

## Challenges to Overcome

This transformation faces significant obstacles:
- Institutional resistance to change
- Digital access inequalities
- Privacy concerns with data collection
- The need for teacher training and adaptation
- The risk of over-reliance on technology

## The Way Forward

Technology alone won't fix education. We need thoughtful integration that:
- Empowers teachers rather than replacing them
- Addresses equity concerns
- Balances screen time with human connection
- Develops both technical and human skills

The future of education isn't about choosing between technology and traditional methods—it's about finding the optimal blend that serves each learner's needs.
    `,
    date: "2024-02-10",
    coverImage:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    tags: ["education", "technology", "ai", "future"],
  },
];
